version: "3.8"
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork

  redis:
    image: "redis:alpine"
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
